title: Yanni IYEZE
logo: "/images/yanni.JPG?raw=true"
description: Data Analyst and Tech enthusiast | Tableau specialist & Data scientist/engineer for fun
show_downloads: true
theme: jekyll-theme-cayman
