title: Yanni IYEZE
logo: "/images/yanni.JPG?raw=true"
description: Hello
# Build settings
markdown: kramdown
theme: jekyll-theme-basically-basic
plugins: # previously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
